#!/bin/sh

if [[ -z $(acpi) ]]; then
  exit
fi

STATE=$(acpi | cut -d ' ' -f 3 | egrep -o '\w+')
PERCENTAGE=$(acpi | cut -d ' ' -f 4 | egrep -o '\w+')
TEXT=":$PERCENTAGE%"

if [[ $STATE = "Discharging" ]]; then
  if [[ $PERCENTAGE -gt 90 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 80 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 70 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 60 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 50 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 40 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 30 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 20 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 10 ]]; then
    echo "$TEXT"
  else
    echo "$TEXT"
  fi
else
  if [[ $PERCENTAGE -ge 98 ]]; then
    echo ":Full"
  elif [[ $PERCENTAGE -gt 90 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 80 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 70 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 60 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 50 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 40 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 30 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 20 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 10 ]]; then
    echo "$TEXT"
  else
    echo "$TEXT"
  fi
fi

